import sys
from pathlib import Path


if __name__ == "__main__":
    sys.path.append(str(Path(__file__).resolve().parents[2]))

from backend.state import ResearchState


async def editor_node(state: ResearchState) -> dict:
    company = state["company_name"]
    briefings = state.get("briefings", {})
    print(f"Editor: compiling final report for {company}")

    report = f"""# {company} — Intelligence Report
*Generated by PrismIntel*

## Executive Summary
This report provides a comprehensive analysis of {company}
across company fundamentals, financials, industry context,
and recent developments.

{briefings.get("company", "No company data available.")}

{briefings.get("financial", "No financial data available.")}

{briefings.get("industry", "No industry data available.")}

{briefings.get("news", "No news data available.")}

## Risk Assessment
*(See risk scores section)*

## Competitive Landscape
*(See competitors section)*
"""
    print(f"Editor: report compiled ({len(report)} chars)")
    return {"final_report": report, "status": "complete"}


if __name__ == "__main__":
    import asyncio
    from backend.state import create_initial_state
    from backend.nodes.briefing import briefing_node

    async def test():
        state = create_initial_state("t001", "Tesla")
        state["curated_docs"] = {
            "company": [],
            "financial": [],
            "industry": [],
            "news": [],
        }
        state = {**state, **(await briefing_node(state))}
        result = await editor_node(state)
        assert "# Tesla" in result["final_report"]
        print(f"✅ Editor: {len(result['final_report'])} chars")
        print(result["final_report"][:300])

    asyncio.run(test())
